/* confdefs.h.  */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define OPTION_NO_ENVIRONMENT 1
#define GNUSTEP_TARGET_MAKEFILES "/mingw/../devlibs/gnustep1201/System/Library/Makefiles"
#define GNUSTEP_TARGET_USER_DEFAULTS_DIR "GNUstep/Defaults"
#define GNUSTEP_TARGET_USER_CONFIG_FILE ".GNUstep.conf"
#define GNUSTEP_TARGET_CONFIG_FILE "./GNUstep.conf"
#define GNUSTEP_TARGET_SYSTEM_APPS "./../../System/Applications"
#define GNUSTEP_TARGET_SYSTEM_ADMIN_APPS "./../../System/Applications/Admin"
#define GNUSTEP_TARGET_SYSTEM_WEB_APPS "./../../System/Library/WebApplications"
#define GNUSTEP_TARGET_SYSTEM_TOOLS "./../../System/Tools"
#define GNUSTEP_TARGET_SYSTEM_ADMIN_TOOLS "./../../System/Tools/Admin"
#define GNUSTEP_TARGET_SYSTEM_LIBRARY "./../../System/Library"
#define GNUSTEP_TARGET_SYSTEM_LIBRARIES "./../../System/Library/Libraries"
#define GNUSTEP_TARGET_SYSTEM_HEADERS "./../../System/Library/Headers"
#define GNUSTEP_TARGET_SYSTEM_DOC "./../../System/Library/Documentation"
#define GNUSTEP_TARGET_SYSTEM_DOC_MAN "./../../System/Library/Documentation/man"
#define GNUSTEP_TARGET_SYSTEM_DOC_INFO "./../../System/Library/Documentation/info"
#define GNUSTEP_TARGET_NETWORK_APPS "./../Applications"
#define GNUSTEP_TARGET_NETWORK_ADMIN_APPS "./../Applications/Admin"
#define GNUSTEP_TARGET_NETWORK_WEB_APPS "./../Library/WebApplications"
#define GNUSTEP_TARGET_NETWORK_TOOLS "./"
#define GNUSTEP_TARGET_NETWORK_ADMIN_TOOLS "./Admin"
#define GNUSTEP_TARGET_NETWORK_LIBRARY "./../Library"
#define GNUSTEP_TARGET_NETWORK_LIBRARIES "./../Library/Libraries"
#define GNUSTEP_TARGET_NETWORK_HEADERS "./../Library/Headers"
#define GNUSTEP_TARGET_NETWORK_DOC "./../Library/Documentation"
#define GNUSTEP_TARGET_NETWORK_DOC_MAN "./../Library/Documentation/man"
#define GNUSTEP_TARGET_NETWORK_DOC_INFO "./../Library/Documentation/info"
#define GNUSTEP_TARGET_LOCAL_APPS "./../Applications"
#define GNUSTEP_TARGET_LOCAL_ADMIN_APPS "./../Applications/Admin"
#define GNUSTEP_TARGET_LOCAL_WEB_APPS "./../Library/WebApplications"
#define GNUSTEP_TARGET_LOCAL_TOOLS "./"
#define GNUSTEP_TARGET_LOCAL_ADMIN_TOOLS "./Admin"
#define GNUSTEP_TARGET_LOCAL_LIBRARY "./../Library"
#define GNUSTEP_TARGET_LOCAL_LIBRARIES "./../Library/Libraries"
#define GNUSTEP_TARGET_LOCAL_HEADERS "./../Library/Headers"
#define GNUSTEP_TARGET_LOCAL_DOC "./../Library/Documentation"
#define GNUSTEP_TARGET_LOCAL_DOC_MAN "./../Library/Documentation/man"
#define GNUSTEP_TARGET_LOCAL_DOC_INFO "./../Library/Documentation/info"
#define GNUSTEP_TARGET_USER_DIR_APPS "GNUstep/Applications"
#define GNUSTEP_TARGET_USER_DIR_ADMIN_APPS "GNUstep/Applications/Admin"
#define GNUSTEP_TARGET_USER_DIR_WEB_APPS "GNUstep/Library/WebApplications"
#define GNUSTEP_TARGET_USER_DIR_TOOLS "GNUstep/Tools"
#define GNUSTEP_TARGET_USER_DIR_ADMIN_TOOLS "GNUstep/Tools/Admin"
#define GNUSTEP_TARGET_USER_DIR_LIBRARY "GNUstep/Library"
#define GNUSTEP_TARGET_USER_DIR_LIBRARIES "GNUstep/Library/Libraries"
#define GNUSTEP_TARGET_USER_DIR_HEADERS "GNUstep/Library/Headers"
#define GNUSTEP_TARGET_USER_DIR_DOC "GNUstep/Library/Documentation"
#define GNUSTEP_TARGET_USER_DIR_DOC_MAN "GNUstep/Library/Documentation/man"
#define GNUSTEP_TARGET_USER_DIR_DOC_INFO "GNUstep/Library/Documentation/info"
#define GNUSTEP_TARGET_SYSTEM_USERS_DIR ""
#define GNUSTEP_TARGET_NETWORK_USERS_DIR ""
#define GNUSTEP_TARGET_LOCAL_USERS_DIR ""
#define _GNU_SOURCE 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define HAVE_OBJC_RUNTIME_H 1
#define HAVE_OBJC_OBJC_H 1
#define HAVE_VISIBILITY_ATTRIBUTE 0
#define BROKEN_SO_REUSEADDR 1
#define SIZEOF_VOIDP 4
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define CON_AUTOLOAD 1
#define HAVE_LOAD_METHOD 1
#define HAVE_OBJC_THREAD_ADD 1
#define HAVE_OBJC_GET_UNINSTALLED_DTABLE 1
#define HAVE_UNEXPECTED 1
#define STDC_HEADERS 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_FLOAT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_WINDOWS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_LIBM 1
#define HAVE_GETLOGIN 1
#define HAVE_RINT 1
#define HAVE_GETOPT 1
#define HAVE_TIME_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TIME 1
#define HAVE_CTIME 1
#define HAVE_TZSET 1
#define HAVE_PTHREAD_H 1
#define SIZEOF_PTHREAD_MUTEX_T 4
#define SIZEOF_PTHREAD_COND_T 4
#define HAVE_VSPRINTF 1
#define VSPRINTF_RETURNS_LENGTH 1
#define HAVE_GETCWD 1
#define HAVE_DIRENT_H 1
#define HAVE_GETOPT_H 1
#define HAVE_MPROTECT 1
#define HAVE_PTS_STREAM_MODULES 0
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRING_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_STDLIB_H 1
#define HAVE_SYS_FILE_H 1
#define HAVE_SYS_FCNTL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UTIME_H 1
#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_ZLIB_H 1
#define HAVE_USLEEP 1
#define HAVE_STRERROR 1
#define HAVE_UINTMAX_T 1
#define HAVE_WCHAR_H 1
#define NEED_WORD_ALIGNMENT 0
#define CMDLINE_TERMINATED 0
#define HAVE_FORWARD2 1
#define USE_LIBFFI 1
/* end confdefs.h.  */
#include "./config/config.ffi.c"