dnl  mpn_bdiv_dbm1c - from x86/atom/sse2 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_bdiv_dbm1c)
define(__gmpn_bdiv_dbm1c, __gmpn_bdiv_dbm1c_atom_sse2)
define(__gmpn_bdiv_dbm1cc,__gmpn_bdiv_dbm1cc_atom_sse2)
define(__gmpn_preinv_bdiv_dbm1c,__gmpn_preinv_bdiv_dbm1c_atom_sse2)
define(__gmpn_bdiv_dbm1c_cps,__gmpn_bdiv_dbm1c_cps_atom_sse2)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_atom_sse2)')


include(.././mpn/x86/atom/sse2/bdiv_dbm1c.asm)

