dnl  mpn_mod_1_1p - from x86/atom/sse2 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_mod_1_1)
define(__gmpn_mod_1_1p, __gmpn_mod_1_1p_atom_sse2)
define(__gmpn_mod_1c_1p,__gmpn_mod_1c_1p_atom_sse2)
define(__gmpn_preinv_mod_1_1p,__gmpn_preinv_mod_1_1p_atom_sse2)
define(__gmpn_mod_1_1p_cps,__gmpn_mod_1_1p_cps_atom_sse2)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_atom_sse2)')


include(.././mpn/x86/atom/sse2/mod_1_1.asm)

