dnl  mpn_copyi - from x86/atom/mmx directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_copyi)
define(__gmpn_copyi, __gmpn_copyi_atom_mmx)
define(__gmpn_copyic,__gmpn_copyic_atom_mmx)
define(__gmpn_preinv_copyi,__gmpn_preinv_copyi_atom_mmx)
define(__gmpn_copyi_cps,__gmpn_copyi_cps_atom_mmx)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_atom_mmx)')


include(.././mpn/x86/atom/mmx/copyi.asm)

