dnl  mpn_copyd - from x86/atom/mmx directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_copyd)
define(__gmpn_copyd, __gmpn_copyd_atom_mmx)
define(__gmpn_copydc,__gmpn_copydc_atom_mmx)
define(__gmpn_preinv_copyd,__gmpn_preinv_copyd_atom_mmx)
define(__gmpn_copyd_cps,__gmpn_copyd_cps_atom_mmx)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_atom_mmx)')


include(.././mpn/x86/atom/mmx/copyd.asm)

