dnl  mpn_submul_1 - from x86/atom/sse2 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_submul_1)
define(__gmpn_submul_1, __gmpn_submul_1_atom_sse2)
define(__gmpn_submul_1c,__gmpn_submul_1c_atom_sse2)
define(__gmpn_preinv_submul_1,__gmpn_preinv_submul_1_atom_sse2)
define(__gmpn_submul_1_cps,__gmpn_submul_1_cps_atom_sse2)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_atom_sse2)')


include(.././mpn/x86/atom/sse2/aorsmul_1.asm)

