/* mpn_gcd_1 - from x86/fat directory for fat binary.
   Generated by configure - DO NOT EDIT. */

#define OPERATION_gcd_1 1
#define __gmpn_gcd_1           __gmpn_gcd_1_fat
#define __gmpn_gcd_1c          __gmpn_gcd_1c_fat
#define __gmpn_preinv_gcd_1  __gmpn_preinv_gcd_1_fat
#define __gmpn_gcd_1_cps     __gmpn_gcd_1_cps_fat

#include ".././mpn/x86/fat/gcd_1.c"

