dnl  mpn_rshift - from x86/k6/mmx directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_rshift)
define(__gmpn_rshift, __gmpn_rshift_k6_mmx)
define(__gmpn_rshiftc,__gmpn_rshiftc_k6_mmx)
define(__gmpn_preinv_rshift,__gmpn_preinv_rshift_k6_mmx)
define(__gmpn_rshift_cps,__gmpn_rshift_cps_k6_mmx)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_k6_mmx)')


include(.././mpn/x86/k6/mmx/rshift.asm)

