dnl  mpn_mod_1_1p - from x86/k7 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_mod_1_1)
define(__gmpn_mod_1_1p, __gmpn_mod_1_1p_k7)
define(__gmpn_mod_1c_1p,__gmpn_mod_1c_1p_k7)
define(__gmpn_preinv_mod_1_1p,__gmpn_preinv_mod_1_1p_k7)
define(__gmpn_mod_1_1p_cps,__gmpn_mod_1_1p_cps_k7)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_k7)')

define(MUL_TOOM22_THRESHOLD,28)
define(MUL_TOOM33_THRESHOLD,85)
define(SQR_TOOM2_THRESHOLD,48)
define(SQR_TOOM3_THRESHOLD,83)
define(BMOD_1_TO_MOD_1_THRESHOLD,24)

include(.././mpn/x86/k7/mod_1_1.asm)

