dnl  mpn_com - from x86/k7/mmx directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_com)
define(__gmpn_com, __gmpn_com_k7_mmx)
define(__gmpn_comc,__gmpn_comc_k7_mmx)
define(__gmpn_preinv_com,__gmpn_preinv_com_k7_mmx)
define(__gmpn_com_cps,__gmpn_com_cps_k7_mmx)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_k7_mmx)')


include(.././mpn/x86/k7/mmx/com.asm)

