dnl  mpn_lshift - from x86/k7/mmx directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_lshift)
define(__gmpn_lshift, __gmpn_lshift_k7_mmx)
define(__gmpn_lshiftc,__gmpn_lshiftc_k7_mmx)
define(__gmpn_preinv_lshift,__gmpn_preinv_lshift_k7_mmx)
define(__gmpn_lshift_cps,__gmpn_lshift_cps_k7_mmx)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_k7_mmx)')


include(.././mpn/x86/k7/mmx/lshift.asm)

