dnl  mpn_divrem_1 - from x86/p6/mmx directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_divrem_1)
define(__gmpn_divrem_1, __gmpn_divrem_1_p6_mmx)
define(__gmpn_divrem_1c,__gmpn_divrem_1c_p6_mmx)
define(__gmpn_preinv_divrem_1,__gmpn_preinv_divrem_1_p6_mmx)
define(__gmpn_divrem_1_cps,__gmpn_divrem_1_cps_p6_mmx)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_p6_mmx)')

define(MUL_TOOM22_THRESHOLD,22)
define(MUL_TOOM33_THRESHOLD,73)
define(SQR_TOOM2_THRESHOLD,30)
define(SQR_TOOM3_THRESHOLD,81)
define(BMOD_1_TO_MOD_1_THRESHOLD,49)

include(.././mpn/x86/p6/mmx/divrem_1.asm)

