dnl  mpn_divexact_1 - from x86/pentium directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_dive_1)
define(__gmpn_divexact_1, __gmpn_divexact_1_pentium)
define(__gmpn_divexact_1c,__gmpn_divexact_1c_pentium)
define(__gmpn_preinv_divexact_1,__gmpn_preinv_divexact_1_pentium)
define(__gmpn_divexact_1_cps,__gmpn_divexact_1_cps_pentium)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_pentium)')

define(MUL_TOOM22_THRESHOLD,16)
define(MUL_TOOM33_THRESHOLD,90)
define(SQR_TOOM2_THRESHOLD,22)
define(SQR_TOOM3_THRESHOLD,122)

include(.././mpn/x86/pentium/dive_1.asm)

