dnl  mpn_bdiv_dbm1c - from x86 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_bdiv_dbm1c)
define(__gmpn_bdiv_dbm1c, __gmpn_bdiv_dbm1c_x86)
define(__gmpn_bdiv_dbm1cc,__gmpn_bdiv_dbm1cc_x86)
define(__gmpn_preinv_bdiv_dbm1c,__gmpn_preinv_bdiv_dbm1c_x86)
define(__gmpn_bdiv_dbm1c_cps,__gmpn_bdiv_dbm1c_cps_x86)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_x86)')


include(.././mpn/x86/bdiv_dbm1c.asm)

