dnl  mpn_cnd_add_n - from x86 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_cnd_add_n)
define(__gmpn_cnd_add_n, __gmpn_cnd_add_n_x86)
define(__gmpn_cnd_add_nc,__gmpn_cnd_add_nc_x86)
define(__gmpn_preinv_cnd_add_n,__gmpn_preinv_cnd_add_n_x86)
define(__gmpn_cnd_add_n_cps,__gmpn_cnd_add_n_cps_x86)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_x86)')


include(.././mpn/x86/cnd_aors_n.asm)

