dnl  mpn_mul_basecase - from x86 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_mul_basecase)
define(__gmpn_mul_basecase, __gmpn_mul_basecase_x86)
define(__gmpn_mul_basecasec,__gmpn_mul_basecasec_x86)
define(__gmpn_preinv_mul_basecase,__gmpn_preinv_mul_basecase_x86)
define(__gmpn_mul_basecase_cps,__gmpn_mul_basecase_cps_x86)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_x86)')


include(.././mpn/x86/mul_basecase.asm)

