dnl  mpn_mod_34lsub1 - from x86 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_mod_34lsub1)
define(__gmpn_mod_34lsub1, __gmpn_mod_34lsub1_x86)
define(__gmpn_mod_34lsub1c,__gmpn_mod_34lsub1c_x86)
define(__gmpn_preinv_mod_34lsub1,__gmpn_preinv_mod_34lsub1_x86)
define(__gmpn_mod_34lsub1_cps,__gmpn_mod_34lsub1_cps_x86)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_x86)')


include(.././mpn/x86/mod_34lsub1.asm)

